### ISSUE TITLE
Tskit table syntax needs some tweaking

### ISSUE THREAD

**Issue by hyanwong** [benjeffery/tskit-book-theme#1]
E.g.

![image](https://user-images.githubusercontent.com/4699014/179277598-16815cb2-c380-41b3-a470-d3933efd9831.png)

**Comment by benjeffery** [comment]
Fixed by https://github.com/benjeffery/tskit-book-theme/commit/58c02fbda1097bf259b28781e2a13daa412d8822
![Screenshot from 2022-07-28 23-14-00](https://user-images.githubusercontent.com/8552/181646427-1e6dcb69-a612-4164-9f13-6e34342a04ab.png)

**Comment by hyanwong** [comment]
Nice!
